#!/usr/bin/env ruby
# encoding: UTF-8
# RunDeck Options Provider - GitHub Repositories
# Brian Dwyer - Intelligent Digital Services - 5/14/16

lib = File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib'))
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

# => Catch Ctrl+C's to avoid stack traces
Signal.trap('INT') { abort }

require 'github-rundeck'

# => Launch the Plugin
GithubRunDeck::CLI.run(ARGV)
